version: '3.7'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - general

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=XXXXXX@163.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - general

  web:
    image: ghcr.dockerproxy.com/dbfu/fluxy-admin-web:main
    container_name: web
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: fluxyadmin.cn
      LETSENCRYPT_HOST: fluxyadmin.cn
      VIRTUAL_PORT: 80
      SERVER_URL: http://server:7001
      FILE_URL: http://file:9000/
    networks:
      - general

  server:
    image: ghcr.dockerproxy.com/dbfu/fluxy-admin-server:main
    container_name: server
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: 12345678
      DB_USERNAME: root
      DB_PASSWORD: 12345678
      DB_HOST: db
      MINIO_HOST: file
      MINIO_SECRET_KEY: 12345678
      MINIO_PORT: 9000
    ports:
      - 7002:7001
    networks:
      general:
        ipv4_address: 172.18.0.200
    depends_on:
      - db
      - redis
      - file

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      
    ports:
      - 3306:3306
    networks:
      - general

  redis:
    image: redis:latest
    container_name: redis
    command: --requirepass 12345678
    restart: unless-stopped
    volumes:
      - /data/redis:/data
    ports:
      - 6379:6379
    networks:
      - general

  file:
    image: minio/minio:latest
    container_name: file
    command: server --console-address :9001 /data
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - /data/minio:/data
      - /etc/localtime:/etc/localtime
    ports:
      - "9009:9001"
    networks:
      - general

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:


networks:
  general:


